#!/bin/bash

USUARIO=$(whoami)

journalctl -o short-iso --no-pager -S "$(date -d '14 days ago' '+%Y-%m-%d')" \
| grep -E "New session|System is powering down|Performing sleep operation|System returned from sleep" \
| awk -v usuario="$USUARIO" -f /usr/local/lib/trabajo.awk